Repository king04aman/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#3 Adding Dijkstra_shortest_path.cpp
  CPP/Dijkstra_shortest_path.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#4 Added name in contributors.md
  CONTRIBUTORS.md
Labels: hacktoberfest

#6 Binary Search Square Root
  CPP/SquareRoot.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#7 Added Sum of Digits of a number
  Java/Sum_Of_Digits_Of_A_Number.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 Added fibonacci series generator function
  Java/Fibonacci_Series.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#9 Sum of digits of a number , Fibonacci series and palindrome
  C/Fibonacci series.c
  C/palindrom or not..c
  C/sum of digit of a number.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#11 Create Pigeonhole_sort.cpp
  CPP/Pigeonhole_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#12 Added Rotate array by K steps
  C/ArrayRotation.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#13 Added Bubble Sort program
  C/bubbleSort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#14 Added Quick Sort Program
  quickSort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 Added calculator program
  C/calculator.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#19 Added insertion and deletion code in C++
  CPP/deletion.cpp
  CPP/insertion.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#20 added a Turtle art file
  Python/art1.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#21 Create Given_Number_Palindrome_or_Not.c
  C/Given_Number_Palindrome_or_Not.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 Create quickSort.c
  C/quickSort.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#27 added code
  Java/SumTwo.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#28 Patch 1
  CONTRIBUTORS.md
  CPP/Find-middle-of-linked-list.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#29 Create floyd.js
  Javascript/floyd.js
Labels: hacktoberfest-accepted, hacktoberfest2022

#31 AmstrongNumber_Checking.java
  Java/AmstrongNumber_Checking.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#32 DifferenceOf_SumandProduct_ofTwoNumbers.java
  Java/DifferenceOf_SumandProduct_ofTwoNumbers.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#33 Added "Write a program to count vowel in a given string" java code
  CONTRIBUTORS.md
  Java/CountVowels.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#34 Create MCM.cpp
  CPP/MCM.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#37 Code in C++ language to multiple all elements in an array of 10 elements
  CPP/multipleofele.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#26 Create check vowels.c
  C/check vowels.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#39 Hacktoberfest-2022
  CPP/Sieve of Eratosthenes.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#40 Create reverse_a_string.cpp
  CPP/reverse_a_string.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#41 I have created python program for swapping values of two variables
  Python/Swap.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#42 Create dp Trapping Rainwater leetcode.cpp
  CPP/dp Trapping Rainwater leetcode.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#44 Two programs in C
  C/Insertion of element in array in C
  C/Swap two elements in C
Labels: hacktoberfest-accepted, hacktoberfest2022

#45 Reverse of a given string using java
  Java/reverse.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#46 Insertion and deletion in an array in JAVA.
  Java/ArrayInsertionDeletion.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#47 Create Armstrong Number.cpp
  CPP/Armstrong  Number.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#50 Create healthmanagement.py
  Python/healthmanagement.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#52 Created vertical_order_traversal.cpp
  CPP/vertical_order_traversal.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#53 Armstrong_Number
  CONTRIBUTORS.md
  Python/Armstrong_Number.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#56 Add 2 javascript programs
  Javascript/palindrome.js
  Javascript/reverseString.js
Labels: hacktoberfest-accepted, hacktoberfest2022

#55 I added Tower Of Hanoi In CPP
  CPP/Tower of Hanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#68 hacktoberfest2022
  CPP/Trees/Check-symmetric-tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#66 Program to find diff between sum and product
  Python/sum.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#65 Added C programs
  C/VariadicFunctions.c
  C/postTransition.c
  C/queryingTheDocument.c
  C/smallTrianglesLargeTriangles.c
  C/sortingArrayOfStrings.c
  C/structuringTheDocument.c
Labels: hacktoberfest-accepted

#61 Create BMI_Calculator.java
  CPP/decimal_to_binary.cpp
  Java/BMI_Calculator.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#62 Merge Sort
  CPP/Merge_Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#63 Create maximum-profit-in-job-scheduling-DFS.cpp
  CPP/Graph/maximum-profit-in-job-scheduling-DFS.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#71 Added Radix Sort in CPP
  CONTRIBUTORS.md
  CPP/Radix_Sort.cpp
Labels: hacktoberfest-accepted

#72 algo to findout anagram using hashmap
  Python/an4gram.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#74 Create armstrong.py
  Python/armstrong.py
Labels: hacktoberfest-accepted

#80 booleanParenthesisDP added
  CPP/booleanParenthesisDP.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#81 Update Fibonacci_Series.java
  Java/Fibonacci_Series.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#109 Add Efficient Tower of Hanoi
  CPP/TowerOfHanoi.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#82 SetMatrixZeroes.cpp added
  CPP/SetMatrixZeroes.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#86 added subset.java file
  Java/SubSet.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#87 Create Swap_values.cpp
  CPP/Swap_values.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#88 added scanner class so that user can input a number
  Java/SumTwo.java
Labels: hacktoberfest-accepted

#90 Create palindrome.js
  CONTRIBUTORS.md
  Javascript/Palindrome.js
Labels: hacktoberfest-accepted, hacktoberfest2022

#93 Fibonacci Series
  Python/Fibonacci.py
Labels: hacktoberfest-accepted

#94 Create Clone Graph.cpp
  CPP/Graph/Clone Graph.cpp
Labels: hacktoberfest-accepted

#95 Armstrong_Numbers
  CPP/Armstrong_Numbers
Labels: hacktoberfest-accepted, hacktoberfest2022

#96 Create Snake.py
  Python/Snake.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#97 Rotate Matrix 90 Degrees Clockwise
  Java/rotational_matrix.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#98 bubble sort in c++
  CPP/Bubble_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#99 binary search using java
  Java/binary_search.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#102 Create Countdown timer
  Python/Countdown timer
Labels: hacktoberfest-accepted, hacktoberfest2022

#103 Single_linked_list
  C/single_linked_list.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#104 added pr to the pending issues
  CPP/decimalToBinary.cpp
  Java/armstrong.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#107 Binary Search Tree insertion, deletion and traversal added
  CONTRIBUTORS.md
  Java/BinarySearchTree.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#110 Create catvsdog.py
  catvsdog.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#105 Added code of Check if Array Is Sorted and Rotated
  CPP/Check_if_Array_Is_Sorted_and_Rotated.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#140 Create Quick Sort
  CPP/Quick Sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#139 Cypher Program
  Python/cypher.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#112 motion detection using python
  Python/Motion detection.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#113 Create GREEDY folder inside CPP and added PRIM's Algo (MST).cpp
  CPP/GREEDY/PRIM's Algo (MST).cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#115 #59 Program to convert decimal into binary.
  CPP/DecToBinary.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#117 Added new file(Armstrong or not)
  CPP/armstrong.cpp
  CPP/binaryto_decimal.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#118 Swap_two_elements_in_C
  CONTRIBUTORS.md
  CPP/Right view of a binary tree.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#127 Binary Search in a array
  CPP/binarySearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#126 Radix Sorting Using C++
  CPP/radix_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#125 Add Atharva Rane to contributers
  CONTRIBUTORS.md
Labels: hacktoberfest2022

#124 Create FloydsTriangle.java
  Java/FloydsTriangle.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#123 Recursion Basic Level Problems
  CPP/Recursion/binary.cpp
  CPP/Recursion/binary.exe
  CPP/Recursion/binarySearch.cpp
  CPP/Recursion/binarySearch.exe
  CPP/Recursion/bubbleSort.cpp
  CPP/Recursion/bubbleSort.exe
  CPP/Recursion/count.cpp
  CPP/Recursion/count.exe
  CPP/Recursion/factorial.cpp
  CPP/Recursion/fibonacciSeries.cpp
  CPP/Recursion/fibonacciSeries.exe
  CPP/Recursion/isSorted.cpp
  CPP/Recursion/linearSearch.cpp
  CPP/Recursion/linearSearch.exe
  CPP/Recursion/nameNtime.cpp
  CPP/Recursion/nameNtime.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#122 Added Leap Year in C
  C/Duck_Number.c
  C/Leap_Year.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#121 added sum of digit of a number
  PHP/Fibonacci.php
  PHP/sum.php
Labels: hacktoberfest-accepted, hacktoberfest2022

#120 Added GoLang sum program to the repo
  GO/sum.go
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#119 Create rock_paper_scissor.cpp
  rock_paper_scissor.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#135 I have added a BMI calculator for hacktoberfest 2022
  Javascript/BMICalculator/index.css
  Javascript/BMICalculator/index.html
  Javascript/BMICalculator/index.js
Labels: hacktoberfest-accepted

#132 added new c program
  C/a.exe
  C/primeNumber.c
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#131 Adding Quick Sort
  CPP/Quick_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#130 Create find the largest item in the binary tree.c
  C/find the largest item in the binary tree.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#129 decimal to binary program in cpp
  CPP/decimal_to_binary.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#128 Updated ArrayRotation.c
  C/ArrayRotation.c
Labels: hacktoberfest-accepted, hacktoberfest2022

#141 Create async-await.js
  Javascript/async-await.js
Labels: hacktoberfest-accepted, hacktoberfest2022

#137 Added C++ program to find all set bits in a number
  CPP/CountSetBits.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#142 Create stl_algo.cpp
  CPP/stl_algo.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#143 Fractional knapsack
  CONTRIBUTORS.md
  CPP/GREEDY/Fractional Knapsacak.cpp
  CPP/GREEDY/Fractional Knapsack
  CPP/radix_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#145 Created floyd_warshall.cpp
  CPP/Graph/floyd_warshall.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#146 206reverseLL.cpp
  CPP/206reverseLL.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022
